In [2]:
import pandas as pd

df = pd.read_csv("/Users/kaviraj/Desktop/GUVI/Project3/classification/c_featured_data.csv")

df

,specialty,appointment_time,gender,no_show,disability,place,appointment_shift,age,under_12_years_old,over_60_years_old,...,rain_intensity,heat_intensity,appointment_date_continuous,Hipertension,Diabetes,Alcoholism,Handcap,Scholarship,SMS_received,day_of_week
0,psychotherapy,17,F,yes,intellectual,Lake Marvinville,afternoon,9.0,1,0,...,no_rain,warm,2020-01-01,0,0,0,0,0,0,Wednesday
1,Unknown,7,M,no,intellectual,ITAPEMA,morning,11.0,1,0,...,no_rain,cold,2020-01-01,0,0,0,0,0,0,Wednesday
2,speech therapy,16,M,no,intellectual,ITAJAÍ,afternoon,8.0,1,0,...,no_rain,warm,2020-01-01,0,0,0,0,0,0,Wednesday
3,speech therapy,14,M,yes,intellectual,Sarahside,afternoon,9.0,1,0,...,moderate,mild,2020-01-01,0,0,0,0,0,1,Wednesday
4,physiotherapy,8,M,no,motor,ITAJAÍ,morning,12.0,0,0,...,no_rain,mild,2020-01-01,0,0,0,0,0,0,Wednesday
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
109552,psychotherapy,16,M,yes,intellectual,Unknown,afternoon,18.0,0,0,...,no_rain,mild,2021-05-11,0,0,0,0,0,0,Tuesday
109553,speech therapy,9,F,yes,motor,Port Georgestad,morning,18.0,0,0,...,moderate,warm,2021-05-11,0,0,0,0,0,0,Tuesday
109554,psychotherapy,13,F,no,intellectual,Erinton,afternoon,8.0,1,0,...,moderate,mild,2021-05-11,0,0,0,0,0,1,Tuesday
109555,physiotherapy,8,F,no,motor,CAMBORIU,morning,7.0,1,0,...,no_rain,warm,2021-05-11,0,0,0,0,0,0,Tuesday
109556,psychotherapy,11,M,no,Unknown,Unknown,morning,12.0,0,0,...,weak,cold,2021-05-12,0,0,0,0,0,0,Wednesday

In [44]:
print(df.columns.tolist())

['specialty', 'appointment_time', 'gender', 'no_show', 'disability', 'place', 'appointment_shift', 'age', 'under_12_years_old', 'over_60_years_old', 'patient_needs_companion', 'average_temp_day', 'average_rain_day', 'max_temp_day', 'max_rain_day', 'rainy_day_before', 'storm_day_before', 'rain_intensity', 'heat_intensity', 'appointment_date_continuous', 'Hipertension', 'Diabetes', 'Alcoholism', 'Handcap', 'Scholarship', 'SMS_received', 'day_of_week']

In [3]:
df.drop(['place','appointment_date_continuous'], axis=1, inplace=True)

# 1. Identify Column types

In [23]:
numerical_cols = df.select_dtypes(include=['int64', 'float64']).columns
categorical_cols = df.select_dtypes(include='object').columns

print("numerical_cols:", numerical_cols)
print("categorical_cols:", categorical_cols)

numerical_cols: Index(['appointment_time', 'age', 'under_12_years_old', 'over_60_years_old',
       'patient_needs_companion', 'average_temp_day', 'average_rain_day',
       'max_temp_day', 'max_rain_day', 'rainy_day_before', 'storm_day_before',
       'Hipertension', 'Diabetes', 'Alcoholism', 'Handcap', 'Scholarship',
       'SMS_received'],
      dtype='object')
categorical_cols: Index(['specialty', 'gender', 'no_show', 'disability', 'place',
       'appointment_shift', 'rain_intensity', 'heat_intensity', 'day_of_week'],
      dtype='object')

In [24]:
for col in ['specialty', 'gender', 'no_show', 'disability', 'place',
            'appointment_shift', 'rain_intensity', 'heat_intensity', 'day_of_week']:
    print(col, df[col].nunique())
    print(col, df[col].unique())

specialty 9
specialty ['psychotherapy' 'Unknown' 'speech therapy' 'physiotherapy'
 'occupational therapy' 'assist' 'pedagogo' 'enf' 'sem especialidade']
gender 3
gender ['F' 'M' 'I']
no_show 2
no_show ['yes' 'no']
disability 3
disability ['intellectual' 'motor' 'Unknown']
place 26290
place ['Lake Marvinville' 'ITAPEMA' 'ITAJAÍ' ... 'West Gregoryport'
 'Reynoldsville' 'Wilcoxstad']
appointment_shift 2
appointment_shift ['afternoon' 'morning']
rain_intensity 4
rain_intensity ['no_rain' 'moderate' 'weak' 'heavy']
heat_intensity 5
heat_intensity ['warm' 'cold' 'mild' 'heavy_warm' 'heavy_cold']
day_of_week 7
day_of_week ['Wednesday' 'Thursday' 'Friday' 'Saturday' 'Sunday' 'Monday' 'Tuesday']

# 2. Encoding

# Label Encoding

In [4]:
from sklearn.preprocessing import LabelEncoder
# Create a LabelEncoder instance
le = LabelEncoder()

# Apply Label Encoding to the 'Gender' column
df['no_show'] = le.fit_transform(df['no_show'])

# Display the DataFrame with the new encoded column
display(df)

,specialty,appointment_time,gender,no_show,disability,appointment_shift,age,under_12_years_old,over_60_years_old,patient_needs_companion,...,storm_day_before,rain_intensity,heat_intensity,Hipertension,Diabetes,Alcoholism,Handcap,Scholarship,SMS_received,day_of_week
0,psychotherapy,17,F,1,intellectual,afternoon,9.0,1,0,1,...,1,no_rain,warm,0,0,0,0,0,0,Wednesday
1,Unknown,7,M,0,intellectual,morning,11.0,1,0,1,...,1,no_rain,cold,0,0,0,0,0,0,Wednesday
2,speech therapy,16,M,0,intellectual,afternoon,8.0,1,0,1,...,1,no_rain,warm,0,0,0,0,0,0,Wednesday
3,speech therapy,14,M,1,intellectual,afternoon,9.0,1,0,1,...,1,moderate,mild,0,0,0,0,0,1,Wednesday
4,physiotherapy,8,M,0,motor,morning,12.0,0,0,0,...,1,no_rain,mild,0,0,0,0,0,0,Wednesday
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
109552,psychotherapy,16,M,1,intellectual,afternoon,18.0,0,0,0,...,1,no_rain,mild,0,0,0,0,0,0,Tuesday
109553,speech therapy,9,F,1,motor,morning,18.0,0,0,0,...,1,moderate,warm,0,0,0,0,0,0,Tuesday
109554,psychotherapy,13,F,0,intellectual,afternoon,8.0,1,0,1,...,1,moderate,mild,0,0,0,0,0,1,Tuesday
109555,physiotherapy,8,F,0,motor,morning,7.0,1,0,1,...,1,no_rain,warm,0,0,0,0,0,0,Tuesday
109556,psychotherapy,11,M,0,Unknown,morning,12.0,0,0,0,...,1,weak,cold,0,0,0,0,0,0,Wednesday

# One-hot Encoder

In [5]:
onehot_cols = ['specialty', 'gender', 'disability', 'appointment_shift', 'day_of_week']

# Apply One-Hot Encoding
df = pd.get_dummies(df, columns = onehot_cols, drop_first = True)

df.head(5)

,appointment_time,no_show,age,under_12_years_old,over_60_years_old,patient_needs_companion,average_temp_day,average_rain_day,max_temp_day,max_rain_day,...,gender_M,disability_intellectual,disability_motor,appointment_shift_morning,day_of_week_Monday,day_of_week_Saturday,day_of_week_Sunday,day_of_week_Thursday,day_of_week_Tuesday,day_of_week_Wednesday
0,17,1,9.0,1,0,1,23.18,0.00,27.5,0.0,...,False,True,False,False,False,False,False,False,False,True
1,7,0,11.0,1,0,1,14.31,0.02,16.5,0.6,...,True,True,False,True,False,False,False,False,False,True
2,16,0,8.0,1,0,1,21.61,0.01,29.9,0.2,...,True,True,False,False,False,False,False,False,False,True
3,14,1,9.0,1,0,1,21.39,0.11,24.1,1.4,...,True,True,False,False,False,False,False,False,False,True
4,8,0,12.0,0,0,0,20.15,0.02,23.1,0.2,...,True,False,True,True,False,False,False,False,False,True

# Ordinal Encoder

In [6]:
from sklearn.preprocessing import OrdinalEncoder

oe = OrdinalEncoder(
    categories=[
        ['no_rain', 'weak', 'moderate', 'heavy'],  # rain_intensity
        ['heavy_cold', 'cold', 'mild', 'warm', 'heavy_warm']  # heat_intensity
    ]
)

df[['rain_intensity', 'heat_intensity']] = oe.fit_transform(
    df[['rain_intensity', 'heat_intensity']]
)

df.head(5)

,appointment_time,no_show,age,under_12_years_old,over_60_years_old,patient_needs_companion,average_temp_day,average_rain_day,max_temp_day,max_rain_day,...,gender_M,disability_intellectual,disability_motor,appointment_shift_morning,day_of_week_Monday,day_of_week_Saturday,day_of_week_Sunday,day_of_week_Thursday,day_of_week_Tuesday,day_of_week_Wednesday
0,17,1,9.0,1,0,1,23.18,0.00,27.5,0.0,...,False,True,False,False,False,False,False,False,False,True
1,7,0,11.0,1,0,1,14.31,0.02,16.5,0.6,...,True,True,False,True,False,False,False,False,False,True
2,16,0,8.0,1,0,1,21.61,0.01,29.9,0.2,...,True,True,False,False,False,False,False,False,False,True
3,14,1,9.0,1,0,1,21.39,0.11,24.1,1.4,...,True,True,False,False,False,False,False,False,False,True
4,8,0,12.0,0,0,0,20.15,0.02,23.1,0.2,...,True,False,True,True,False,False,False,False,False,True

In [7]:
df

,appointment_time,no_show,age,under_12_years_old,over_60_years_old,patient_needs_companion,average_temp_day,average_rain_day,max_temp_day,max_rain_day,...,gender_M,disability_intellectual,disability_motor,appointment_shift_morning,day_of_week_Monday,day_of_week_Saturday,day_of_week_Sunday,day_of_week_Thursday,day_of_week_Tuesday,day_of_week_Wednesday
0,17,1,9.0,1,0,1,23.18,0.00,27.5,0.0,...,False,True,False,False,False,False,False,False,False,True
1,7,0,11.0,1,0,1,14.31,0.02,16.5,0.6,...,True,True,False,True,False,False,False,False,False,True
2,16,0,8.0,1,0,1,21.61,0.01,29.9,0.2,...,True,True,False,False,False,False,False,False,False,True
3,14,1,9.0,1,0,1,21.39,0.11,24.1,1.4,...,True,True,False,False,False,False,False,False,False,True
4,8,0,12.0,0,0,0,20.15,0.02,23.1,0.2,...,True,False,True,True,False,False,False,False,False,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
109552,16,1,18.0,0,0,0,18.97,0.00,25.6,0.2,...,True,True,False,False,False,False,False,False,True,False
109553,9,1,18.0,0,0,0,24.46,0.23,31.4,8.7,...,False,False,True,True,False,False,False,False,True,False
109554,13,0,8.0,1,0,1,20.88,0.00,23.8,5.1,...,False,True,False,False,False,False,False,False,True,False
109555,8,0,7.0,1,0,1,24.89,0.00,28.8,0.0,...,False,False,True,True,False,False,False,False,True,False
109556,11,0,12.0,0,0,0,18.85,0.16,20.8,2.0,...,True,False,False,True,False,False,False,False,False,True

In [90]:
df.to_csv("c_encoded_dataset.csv", index=False)